// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/geo-sovereignty/AIToolkit.tsx": () => import("../components/mockups/geo-sovereignty/AIToolkit.tsx"),
  "./components/mockups/geo-sovereignty/ContentLibrary.tsx": () => import("../components/mockups/geo-sovereignty/ContentLibrary.tsx"),
  "./components/mockups/geo-sovereignty/HomeDashboard.tsx": () => import("../components/mockups/geo-sovereignty/HomeDashboard.tsx"),
  "./components/mockups/geo-sovereignty/MapLogin.tsx": () => import("../components/mockups/geo-sovereignty/MapLogin.tsx"),
  "./components/mockups/geo-sovereignty/SMEReview.tsx": () => import("../components/mockups/geo-sovereignty/SMEReview.tsx")
};
