/**
 * Streaming client for the PPT Skills Agent (POST /api/chat).
 *
 * Configure the agent base URL at build time via the VITE_PPT_AGENT_URL env var.
 * Falls back to http://localhost:8080 for local development.
 */

declare const __PPT_AGENT_BASE__: string;

function getPptAgentBase(): string {
  // Vite replaces import.meta.env at build time; guard for non-Vite runtimes.
  try {
    const url =
      // @ts-ignore - Vite env
      (import.meta as { env?: Record<string, string> }).env?.VITE_PPT_AGENT_URL;
    if (url) return url.replace(/\/+$/, "");
  } catch {
    // non-Vite runtime — fall through
  }
  return "http://localhost:8080";
}

const PPT_AGENT_BASE = getPptAgentBase();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PptChatOptions {
  /** Session ID for multi-turn memory. Auto-generated by the agent on first call. */
  sessionId?: string | null;
  /** Pre-select a template (e.g. "sales-enablement-2022"). */
  templateId?: string | null;
  /**
   * BCP-47 language tag for both chat replies and slide content
   * (e.g. "fr", "de", "ja"). Omit to let the agent auto-detect from the message.
   */
  language?: string | null;
}

export type PptChunkType = "session" | "text" | "tool" | "done" | "error";

export interface PptChunk {
  type: PptChunkType;
  content: string;
}

// ---------------------------------------------------------------------------
// SSE streaming generator
// ---------------------------------------------------------------------------

/**
 * Stream a conversation turn with the PPT agent.
 *
 * Yields {@link PptChunk} objects:
 * - `session` — carries the resolved session_id (always the first chunk)
 * - `text`    — LLM token(s); accumulate to build the full reply
 * - `tool`    — tool completion status line (e.g. "[list_templates] ...")
 * - `done`    — stream finished normally
 * - `error`   — agent reported an error; `content` is the message
 *
 * @example
 * ```ts
 * let reply = "";
 * for await (const chunk of streamPptChat("Build a 5-slide OpenShift deck", { language: "fr" })) {
 *   if (chunk.type === "session") sessionId = chunk.content;
 *   if (chunk.type === "text") reply += chunk.content;
 * }
 * ```
 */
export async function* streamPptChat(
  message: string,
  options: PptChatOptions = {},
): AsyncGenerator<PptChunk> {
  let response: Response;

  try {
    response = await fetch(`${PPT_AGENT_BASE}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message,
        session_id: options.sessionId ?? undefined,
        template_id: options.templateId ?? undefined,
        language: options.language ?? undefined,
      }),
    });
  } catch (err) {
    yield { type: "error", content: `Network error: ${err instanceof Error ? err.message : String(err)}` };
    return;
  }

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    yield { type: "error", content: `HTTP ${response.status}: ${text || response.statusText}` };
    return;
  }

  if (!response.body) {
    yield { type: "error", content: "Response body is empty" };
    return;
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });

      // SSE lines are separated by \n; keep incomplete line in buffer
      const lines = buffer.split("\n");
      buffer = lines.pop() ?? "";

      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;

        const data = line.slice(6);

        if (data === "[done]") {
          yield { type: "done", content: "" };
          return;
        }

        if (data.startsWith("[error]")) {
          yield { type: "error", content: data.slice(7).trim() };
          return;
        }

        if (data.startsWith("session_id=")) {
          yield { type: "session", content: data.slice(11) };
          continue;
        }

        // Tool status lines start with "[tool_name]"
        if (/^\[[^\]]+\]/.test(data)) {
          yield { type: "tool", content: data };
          continue;
        }

        // The agent escapes newlines inside a single SSE data field as "data: "
        // (see app.py _sse_generator). Restore them.
        yield { type: "text", content: data === "" ? "\n" : data };
      }
    }
  } finally {
    reader.releaseLock();
  }

  yield { type: "done", content: "" };
}

// ---------------------------------------------------------------------------
// Template list helper
// ---------------------------------------------------------------------------

export interface PptTemplate {
  template_id: string;
  name: string;
  primary_color: string | null;
  heading_font: string | null;
  body_font: string | null;
}

/** Fetch the list of available presentation templates. */
export async function fetchPptTemplates(): Promise<PptTemplate[]> {
  const response = await fetch(`${PPT_AGENT_BASE}/api/templates`);
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return response.json() as Promise<PptTemplate[]>;
}
